### ISSUE TITLE
About macro functions...

### ISSUE THREAD

**Issue by ZhuinZ** [lichenaut/DatapackLoader#8]
It's seems that I can't use macro functions and commands in a datapack with the plugin. Please help me!

**Comment by ZhuinZ** [comment]
[resources.zip](https://github.com/user-attachments/files/16041550/resources.zip)
The test datapack is here.
In a singleplayer game it works well. But in a server with DatapackLoader, all the commands in every function can work except the macro command. I'm not able to /function the function with the macro command but the other commands in it work well.

**Comment by lichenaut** [comment]
By macro, you mean your function? The import command can only be executed via console, and the dltp command can only be executed via player.
